name: dwmpr
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  http: ^0.11.3

  font_awesome_flutter: ^7.0.0
  bidirectional_scroll_view: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true