name: dwmpr
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  http: ^0.11.3

  font_awesome_flutter: ^7.0.0
  bidirectional_scroll_view: ^0.0.5

  build_runner: ^0.8.10
  built_value: ^5.4.0
  built_value_generator: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family: RobotoMono
        fonts:
          - asset: assets/RobotoMono-Medium.ttf